### ISSUE TITLE
[FEATURE] Add docker-compose file for local testing

### ISSUE THREAD

**Issue by sanjeevtripurari** [codingkatty/mathpylearn#97]
**Adding docker-compose file for web page testing.**
Having docker-compose file will help do local testing of the web application, we can ignore pushing this docker-compose file to production 

**Sample View of docker-compose file**
Having simple file, we can enhance it if we intent to run the application in docker containers.

**Requiremets:**
- Install docker desktop on your windows machine
- on command prompt then just have to run
- docker-compose up

**Sample docker-compose file**

```
services:
  web: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
volumes:
  webdata:
    driver: local
```

**Why it is required, as many contributors would be doing changes, they can check locally and push the change**

We should be able to view the in our local browser
http://localhost/

![image](https://github.com/user-attachments/assets/409bb28e-c8e7-40a2-b10e-51f81c129db0)
![image](https://github.com/user-attachments/assets/67020cb2-91ce-4247-b1eb-966e560371be)
